config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods, only: %i[index new create destroy]
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  delete '/destroy_recipe/:recipe_id/foods/:id', to: 'recipe_foods#destroy'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy, class_name: 'RecipeFood'
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  def foods_counter
    recipe_foods.count
  end

  def foods_total_price
    total_price = 0

    recipe_foods.each do |recipe_food|
      total_price += recipe_food.food.price
    end

    total_price
  end

  def missing_foods
    recipe_foods.select do |recipe_food|
      recipe_food.quantity.positive? && recipe_food.food.quantity < recipe_food.quantity
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update]

  def index
    @recipes = Recipe.includes([:user]).where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def update
    return unless @recipe.update(recipe_params)

    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
      format.js # Handles AJAX response
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to user_recipes_path(current_user.id), notice: 'Recipe Added successfully!'
    else
      # render :show
      render :new, status: 422
    end
  end

  def show
    @recipe = Recipe.includes([:user]).find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path
  end

  def public_list
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def public
    @public_recipes = Recipe.includes(:recipe_foods, :user).where(public: true).order('created_at DESC')
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    text = @recipe.public? ? 'public' : 'private'

    if @recipe.save
      flash[:notice] = "#{@recipe.name} is now #{text}!"
    elsif @recipe.errors.any?
      flash[:alert] = @recipe.errors.full_messages.first
    end
    redirect_to user_recipe_path(id: @recipe.id, user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def shopping_list
    @user = current_user
    @recipes = @user.recipes.includes(recipe_foods: :food)

    @missing_foods = RecipeFood.includes(food: :user)
      .where(recipe: @recipes)
      .select('foods.*, recipe_foods.quantity AS recipe_food_quantity')
      .to_a

    @total_food_items = @missing_foods.sum(&:recipe_food_quantity)
    @total_price = @missing_foods.sum { |food| food.recipe_food_quantity * food.price }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_checkbox.html.erb
<div class="container">
  <h1 class="text-center mt-4 mb-4">Shopping List</h1>
  <div class="row">
    <div class="col-12 d-flex justify-content-center align-items-center shop-title">
      <span class="mr-3">
        Amount of food items to buy: <span><%= @missing_foods.length %></span>
      </span>
      <span>
        Total value of food needed: <span>$<%= @missing_foods.map { |r| r.food.price * (r.quantity - r.food.quantity) }.sum %></span>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table food__table">
        <thead>
          <tr class="foods__table-header-row">
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @missing_foods.each do |missing_food| %>
            <tr class="foods__table-body-row">
              <td><%= missing_food.food.name %></td>
              
              <% if missing_food.food.user_id == current_user.id %>
                <td><%= missing_food.quantity - missing_food.food.quantity %> <%= missing_food.food.measurement_unit %></td>
              <% else %>
                <td><%= missing_food.quantity %> <%= missing_food.food.measurement_unit %></td>
              <% end %>
              
              <td>$<%= missing_food.food.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<h1>Recipes</h1>

<% if @recipes.empty? %>
  <p>There are no recipes yet.</p>
<% else %>
  <ul>
    <% @recipes.each do |recipe| %>
      <li>
        <%= link_to recipe.name, recipe_path(recipe) %>
        <% if current_user == recipe.user %>
          | <%= link_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="mb-4">My Recipes</h1>
  <%= link_to "Add New Recipe", new_user_recipe_path, class: "btn btn-primary mb-2" %>

  <% if @recipes.empty? %>
    <p>You have no recipes yet.</p>
  <% else %>
    <ul class="list-group">
      <% @recipes.each do |recipe| %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between align-items-start">
            <div class>
              <h3><%= recipe.name %></h3>
              <div class="d-flex">
              <%= link_to "View Recipe", user_recipe_path(id: recipe.id, user_id: recipe.user.id), class: "btn btn-info m-3 ms-4" %>
              <% if current_user == recipe.user %>
                <%= button_to "Delete", user_recipe_path(recipe.user, recipe.id), method: :delete, class: "btn btn-danger m-3 ms-4" %>
              <% end %>
            </div>
            </div>
            <div>
              <p><%= recipe.description %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1 class="mb-4">Create a New Recipe</h1>
  
  <% if @recipe.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(@recipe.errors.count, "error") %> found:</p>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @recipe, url: "/users/#{current_user.id}/recipes", method: :post do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :preparation_time, class: "form-label" %>
      <%= form.text_field :preparation_time, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :cooking_time, class: "form-label" %>
      <%= form.text_field :cooking_time, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-check mb-3">
      <%= form.check_box :public, class: "form-check-input" %>
      <%= form.label "Public", class: "form-check-label" %>
    </div>

    <div class="mb-3">
      <%= form.submit "Create Recipe", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/recipes/public.html.erb
<h1 class="text-center">Public Recipe</h1>
<section class="container">
  <% @public_recipes.each do |recipe| %>
    <div class="card mb-3" style="max-width: 50rem;">
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to recipe.name, root_path %>
        </h5>
        <p class="text-end">
          <span class="me-2">Total food items:</span>
          <%= recipe.recipe_foods.length %>
        </p>
        <p>By: <%= recipe.user.present? ? recipe.user.name : 'Unknown User' %></p>
        <p class="text-end">
          <span class="me-2">Total price:</span>
          $<%= recipe.foods_total_price %>
        </p>
      </div>
    </div>
  <% end %>
</section>

app/views/recipes/public_list.html.erb
<h1>Public Recipe List</h1>

<ul>
  <% @public_recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<section class="container">
  <h1 class="text-center mb-5"><%= @recipe.name %></h1>
  <span class="badge badge-primary">Private</span>
  <div class="recipe-info d-flex justify-content-around col-md-12">
    <div>
      <h5>Preparation time: <%= @recipe.preparation_time %></h5>
      <h5>Cooking time: <%= @recipe.cooking_time %></h5>
      <div>
        <h3 class="mt-5">Description</h3>
        <p><%= @recipe.description %></p>
      </div>
    </div>
    <div class="recipe-stat col-md-3">
       <h3><% if @recipe.public? %>Public<%else%>Private<%end%></h2>
       <% if @recipe.user == current_user %>
        <label class="switch">
          <input type="checkbox" <%= @recipe.public? ? 'checked' : '' %> disabled>
          <span class="slider round"></span>
        </label>
      <% end %>
      <% if @recipe.user == current_user %>
        <%= button_to @recipe.public? ? 'Make Private' : 'Make Public', toggle_recipe_path(@recipe.id), method: :put, remote: true ,
              class: 'btn btn' %>
      <%else%>
      <p> Be Authorize </p>
      <%end%>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-around">
    <%= link_to "Generate shopping list", general_shopping_list_path, class: 'btn btn-info' %>
    <% if @recipe.user == current_user %>
      <%= link_to "Add ingredient", new_user_recipe_recipe_food_path(@recipe.user, @recipe), class: "btn btn-primary" %>
    <% end %>
  </div>
  <table class="table table-striped table-bordered mt-5 text-center">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe.recipe_foods.each do |ingredient| %>
    <tr>
      <th scope="row"><%= ingredient.food.name %></th>
      <td><%= ingredient.quantity %></td>
      <td>$ <%= ingredient.quantity* ingredient.food.price %></td>
      <td>
        <div class="d-flex justify-content-center gap-3">
          <%= button_to "Delete", "/destroy_recipe/#{@recipe.id}/foods/#{ingredient.food.id}", method: :delete, class: "btn btn-danger" %>
          <%= link_to "Edit", edit_user_recipe_recipe_food_path(@recipe.user, @recipe, ingredient), class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
    <% end %>
    <tr>
  </tbody>
</table>
</section>