config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods, only: %i[index new create destroy]
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  delete '/destroy_recipe/:recipe_id/foods/:id', to: 'recipe_foods#destroy'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def shopping_list
    @user = current_user
    @recipes = @user.recipes.includes(recipe_foods: :food)

    @all_recipes_foods = @recipes.map(&:recipe_foods).flatten

    @missing_foods = @all_recipes_foods.select { |recipe| recipe.quantity > recipe.food.quantity }

    @total_food_items = @missing_foods.sum(&:quantity)
    @total_price = @missing_foods.sum { |recipe_food| recipe_food.quantity * recipe_food.food.price }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_nav.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Recipes', user_recipes_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Public Recipes', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Shopping List', general_shopping_list_path, class: 'nav-link' %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Public Recipes', root_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </nav>
</div>

app/views/users/shopping_list.html.erb
<div class="container">
  <h1 class="text-center mt-4 mb-4">Shopping List</h1>
  <div class="row">
    <div class="col-12 d-flex justify-content-center align-items-center shop-title">
      <span class="mr-3">
        Amount of food items to buy:  <span><%= @missing_foods.length %></span>
      </span>
      <span class="ml-5">
        Total value of food needed:  <span>$<%= @missing_foods.map { |r| r.food.price * (r.quantity - r.food.quantity) }.sum %></span>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table food__table">
        <thead>
          <tr class="foods__table-header-row">
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @missing_foods.each do |missing_food| %>
            <tr class="foods__table-body-row">
              <td><%= missing_food.food.name %></td>
              
              <% if missing_food.food.user_id == current_user.id %>
                <td><%= missing_food.quantity - missing_food.food.quantity %> <%= missing_food.food.measurement_unit %></td>
              <% else %>
                <td><%= missing_food.quantity %> <%= missing_food.food.measurement_unit %></td>
              <% end %>
              
              <td>$<%= missing_food.food.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>