config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods, only: %i[index new create destroy]
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  delete '/destroy_recipe/:recipe_id/foods/:id', to: 'recipe_foods#destroy'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :food_id, presence: true
  validates :quantity, presence: true, numericality: { integer: true, greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe, only: %i[create new]

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe
    if @recipe_food.save
      redirect_to user_recipe_path(id: @recipe.id, user_id: @recipe.user.id), notice: 'Food item added to the recipe.'
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find_by(food_id: params[:id], recipe_id: params[:recipe_id])
    p @recipe_food
    if @recipe_food.destroy
      redirect_to(request.referrer || root_path)
    else
      flash[:error] = 'error'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/new.html.erb
<div class="container">
  <%= form_with(model: @recipe_food, url: user_recipe_recipe_foods_path(@recipe), method: :post) do |f| %>
    <div class="mb-3">
      <%= f.label :food_id, class: "form-label" %>
      <%= f.collection_select :food_id, Food.all, :id, :name, prompt: true, class: "form-control" %>
    </div>
  
    <div class="mb-3">
      <%= f.label :quantity, class: "form-label" %>
      <%= f.number_field :quantity, class: "form-control" %>
    </div>
  
    <div class="mb-3">
      <%= f.submit "Add Food", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>